const BOOKS = [
  // history - Chinese (~75 books)
  { title: "新加坡华人史", author: "柯木林", cat: "history", lang: "中文", tags: ["历史", "华人"], color: "linear-gradient(135deg,#0f4c81,#1a6bb5)", status: "available", rating: 4.5, year: 2015 },
  { title: "从甘榜到都市：新加坡的变迁", author: "许源泰", cat: "history", lang: "中文", tags: ["历史", "新加坡"], color: "linear-gradient(135deg,#7c3aed,#a855f7)", status: "available", rating: 4.3, year: 2010 },
  { title: "李光耀回忆录", author: "李光耀", cat: "history", lang: "中文", tags: ["历史", "政治"], color: "linear-gradient(135deg,#dc2626,#f97316)", status: "borrowed", rating: 4.8, year: 2000 },
  { title: "新加坡建国史", author: "陈荣照", cat: "history", lang: "中文", tags: ["历史", "建国"], color: "linear-gradient(135deg,#059669,#10b981)", status: "available", rating: 4.4, year: 2005 },
  { title: "东南亚华人社会", author: "王赓武", cat: "history", lang: "中文", tags: ["历史", "东南亚"], color: "linear-gradient(135deg,#0891b2,#06b6d4)", status: "available", rating: 4.6, year: 2008 },
  { title: "中国近代史", author: "徐中约", cat: "history", lang: "中文", tags: ["历史", "中国"], color: "linear-gradient(135deg,#be185d,#ec4899)", status: "available", rating: 4.7, year: 2002 },
  { title: "二战时期的新加坡", author: "黄坚立", cat: "history", lang: "中文", tags: ["历史", "战争"], color: "linear-gradient(135deg,#92400e,#d97706)", status: "borrowed", rating: 4.5, year: 2012 },
  { title: "马来亚共产党史", author: "陈平", cat: "history", lang: "中文", tags: ["历史", "政治"], color: "linear-gradient(135deg,#1e40af,#3b82f6)", status: "available", rating: 4.2, year: 2003 },
  { title: "新加坡潮州人", author: "庄钦永", cat: "history", lang: "中文", tags: ["历史", "华人"], color: "linear-gradient(135deg,#065f46,#34d399)", status: "available", rating: 4.1, year: 2007 },
  { title: "世界文明史", author: "威尔·杜兰特", cat: "history", lang: "中文", tags: ["历史", "文明"], color: "linear-gradient(135deg,#374151,#6b7280)", status: "available", rating: 4.9, year: 2001 },
  { title: "明朝那些事儿", author: "当年明月", cat: "history", lang: "中文", tags: ["历史", "中国"], color: "linear-gradient(135deg,#7c2d12,#ea580c)", status: "borrowed", rating: 4.8, year: 2009 },
  { title: "人类简史", author: "尤瓦尔·赫拉利", cat: "history", lang: "中文", tags: ["历史", "人类"], color: "linear-gradient(135deg,#4c1d95,#7c3aed)", status: "available", rating: 4.9, year: 2014 },
  { title: "新加坡客家人", author: "安焕然", cat: "history", lang: "中文", tags: ["历史", "华人"], color: "linear-gradient(135deg,#134e4a,#0d9488)", status: "available", rating: 4.0, year: 2011 },
  { title: "亚洲的崛起", author: "基肖尔·马赫布巴尼", cat: "history", lang: "中文", tags: ["历史", "亚洲"], color: "linear-gradient(135deg,#1e3a5f,#2563eb)", status: "available", rating: 4.3, year: 2013 },
  { title: "新加坡福建人", author: "颜清湟", cat: "history", lang: "中文", tags: ["历史", "华人"], color: "linear-gradient(135deg,#831843,#db2777)", status: "available", rating: 4.2, year: 2006 },
  { title: "太平洋战争史", author: "约翰·托兰", cat: "history", lang: "中文", tags: ["历史", "战争"], color: "linear-gradient(135deg,#0f4c81,#1a6bb5)", status: "available", rating: 4.6, year: 2004 },
  { title: "新加坡独立之路", author: "吴俊刚", cat: "history", lang: "中文", tags: ["历史", "新加坡"], color: "linear-gradient(135deg,#7c3aed,#a855f7)", status: "reserve", rating: 4.4, year: 2015 },
  { title: "东南亚史", author: "霍尔", cat: "history", lang: "中文", tags: ["历史", "东南亚"], color: "linear-gradient(135deg,#dc2626,#f97316)", status: "available", rating: 4.5, year: 2003 },
  { title: "新加坡广东人", author: "刘子政", cat: "history", lang: "中文", tags: ["历史", "华人"], color: "linear-gradient(135deg,#059669,#10b981)", status: "available", rating: 4.1, year: 2009 },
  { title: "中华文明五千年", author: "冯天瑜", cat: "history", lang: "中文", tags: ["历史", "文明"], color: "linear-gradient(135deg,#0891b2,#06b6d4)", status: "borrowed", rating: 4.7, year: 2007 },
  { title: "新加坡海南人", author: "符诗专", cat: "history", lang: "中文", tags: ["历史", "华人"], color: "linear-gradient(135deg,#be185d,#ec4899)", status: "available", rating: 4.0, year: 2010 },
  { title: "日据时期的新加坡", author: "蔡史君", cat: "history", lang: "中文", tags: ["历史", "战争"], color: "linear-gradient(135deg,#92400e,#d97706)", status: "available", rating: 4.3, year: 2008 },
  { title: "新加坡政治史", author: "廖建裕", cat: "history", lang: "中文", tags: ["历史", "政治"], color: "linear-gradient(135deg,#1e40af,#3b82f6)", status: "available", rating: 4.4, year: 2012 },
  { title: "宋朝那些事", author: "吴蔚", cat: "history", lang: "中文", tags: ["历史", "中国"], color: "linear-gradient(135deg,#065f46,#34d399)", status: "available", rating: 4.2, year: 2011 },
  { title: "新加坡经济发展史", author: "陈荣照", cat: "history", lang: "中文", tags: ["历史", "经济"], color: "linear-gradient(135deg,#374151,#6b7280)", status: "reserve", rating: 4.5, year: 2014 },
  { title: "唐朝历史", author: "孟宪实", cat: "history", lang: "中文", tags: ["历史", "中国"], color: "linear-gradient(135deg,#7c2d12,#ea580c)", status: "available", rating: 4.3, year: 2006 },
  { title: "新加坡移民史", author: "柯木林", cat: "history", lang: "中文", tags: ["历史", "移民"], color: "linear-gradient(135deg,#4c1d95,#7c3aed)", status: "available", rating: 4.4, year: 2016 },
  { title: "亚洲金融危机回顾", author: "吴作栋", cat: "history", lang: "中文", tags: ["历史", "经济"], color: "linear-gradient(135deg,#134e4a,#0d9488)", status: "available", rating: 4.1, year: 2008 },
  { title: "新加坡宗教史", author: "李焯然", cat: "history", lang: "中文", tags: ["历史", "宗教"], color: "linear-gradient(135deg,#1e3a5f,#2563eb)", status: "available", rating: 4.2, year: 2013 },
  { title: "清朝历史", author: "戴逸", cat: "history", lang: "中文", tags: ["历史", "中国"], color: "linear-gradient(135deg,#831843,#db2777)", status: "borrowed", rating: 4.6, year: 2005 },
  { title: "新加坡教育史", author: "许福吉", cat: "history", lang: "中文", tags: ["历史", "教育"], color: "linear-gradient(135deg,#0f4c81,#1a6bb5)", status: "available", rating: 4.3, year: 2017 },
  { title: "二十世纪中国史", author: "金冲及", cat: "history", lang: "中文", tags: ["历史", "中国"], color: "linear-gradient(135deg,#7c3aed,#a855f7)", status: "available", rating: 4.5, year: 2009 },
  { title: "新加坡港口史", author: "黄坚立", cat: "history", lang: "中文", tags: ["历史", "新加坡"], color: "linear-gradient(135deg,#dc2626,#f97316)", status: "available", rating: 4.0, year: 2011 },
  { title: "世界近代史", author: "刘宗绪", cat: "history", lang: "中文", tags: ["历史", "世界"], color: "linear-gradient(135deg,#059669,#10b981)", status: "available", rating: 4.4, year: 2004 },
  { title: "新加坡华文教育史", author: "庄钦永", cat: "history", lang: "中文", tags: ["历史", "教育"], color: "linear-gradient(135deg,#0891b2,#06b6d4)", status: "reserve", rating: 4.3, year: 2018 },
  { title: "汉朝历史", author: "翦伯赞", cat: "history", lang: "中文", tags: ["历史", "中国"], color: "linear-gradient(135deg,#be185d,#ec4899)", status: "available", rating: 4.5, year: 2007 },
  { title: "新加坡社会史", author: "廖建裕", cat: "history", lang: "中文", tags: ["历史", "社会"], color: "linear-gradient(135deg,#92400e,#d97706)", status: "available", rating: 4.2, year: 2015 },
  { title: "中国历史地图集", author: "谭其骧", cat: "history", lang: "中文", tags: ["历史", "地理"], color: "linear-gradient(135deg,#1e40af,#3b82f6)", status: "available", rating: 4.7, year: 2002 },
  { title: "新加坡建筑史", author: "陈煜", cat: "history", lang: "中文", tags: ["历史", "建筑"], color: "linear-gradient(135deg,#065f46,#34d399)", status: "available", rating: 4.1, year: 2016 },
  { title: "秦始皇传", author: "张分田", cat: "history", lang: "中文", tags: ["历史", "中国"], color: "linear-gradient(135deg,#374151,#6b7280)", status: "borrowed", rating: 4.4, year: 2010 },
  { title: "新加坡文化史", author: "许源泰", cat: "history", lang: "中文", tags: ["历史", "文化"], color: "linear-gradient(135deg,#7c2d12,#ea580c)", status: "available", rating: 4.3, year: 2019 },
  { title: "东南亚近代史", author: "尼古拉斯·塔林", cat: "history", lang: "中文", tags: ["历史", "东南亚"], color: "linear-gradient(135deg,#4c1d95,#7c3aed)", status: "available", rating: 4.5, year: 2006 },
  { title: "新加坡军事史", author: "吴俊刚", cat: "history", lang: "中文", tags: ["历史", "军事"], color: "linear-gradient(135deg,#134e4a,#0d9488)", status: "available", rating: 4.2, year: 2014 },
  { title: "中国改革开放史", author: "萧冬连", cat: "history", lang: "中文", tags: ["历史", "中国"], color: "linear-gradient(135deg,#1e3a5f,#2563eb)", status: "available", rating: 4.6, year: 2012 },
  { title: "新加坡法律史", author: "陈荣照", cat: "history", lang: "中文", tags: ["历史", "法律"], color: "linear-gradient(135deg,#831843,#db2777)", status: "reserve", rating: 4.1, year: 2017 },
  { title: "三国历史真相", author: "方诗铭", cat: "history", lang: "中文", tags: ["历史", "中国"], color: "linear-gradient(135deg,#0f4c81,#1a6bb5)", status: "available", rating: 4.5, year: 2008 },
  { title: "新加坡外交史", author: "比拉哈里", cat: "history", lang: "中文", tags: ["历史", "外交"], color: "linear-gradient(135deg,#7c3aed,#a855f7)", status: "available", rating: 4.4, year: 2020 },
  { title: "印度文明史", author: "罗米拉·塔帕尔", cat: "history", lang: "中文", tags: ["历史", "文明"], color: "linear-gradient(135deg,#dc2626,#f97316)", status: "available", rating: 4.3, year: 2005 },
  { title: "新加坡金融史", author: "黄坚立", cat: "history", lang: "中文", tags: ["历史", "金融"], color: "linear-gradient(135deg,#059669,#10b981)", status: "available", rating: 4.2, year: 2018 },
  { title: "罗马帝国衰亡史", author: "爱德华·吉本", cat: "history", lang: "中文", tags: ["历史", "世界"], color: "linear-gradient(135deg,#0891b2,#06b6d4)", status: "borrowed", rating: 4.8, year: 2003 },
  { title: "新加坡华人社团史", author: "柯木林", cat: "history", lang: "中文", tags: ["历史", "华人"], color: "linear-gradient(135deg,#be185d,#ec4899)", status: "available", rating: 4.3, year: 2021 },
  { title: "中国古代史", author: "朱绍侯", cat: "history", lang: "中文", tags: ["历史", "中国"], color: "linear-gradient(135deg,#92400e,#d97706)", status: "available", rating: 4.4, year: 2001 },
  { title: "新加坡医疗史", author: "许福吉", cat: "history", lang: "中文", tags: ["历史", "医疗"], color: "linear-gradient(135deg,#1e40af,#3b82f6)", status: "available", rating: 4.0, year: 2019 },
  { title: "第二次世界大战史", author: "温斯顿·丘吉尔", cat: "history", lang: "中文", tags: ["历史", "战争"], color: "linear-gradient(135deg,#065f46,#34d399)", status: "available", rating: 4.9, year: 2004 },
  { title: "新加坡宗乡会馆史", author: "庄钦永", cat: "history", lang: "中文", tags: ["历史", "华人"], color: "linear-gradient(135deg,#374151,#6b7280)", status: "reserve", rating: 4.1, year: 2022 },
  { title: "中国现代史", author: "费正清", cat: "history", lang: "中文", tags: ["历史", "中国"], color: "linear-gradient(135deg,#7c2d12,#ea580c)", status: "available", rating: 4.7, year: 2006 },
  { title: "新加坡工人运动史", author: "廖建裕", cat: "history", lang: "中文", tags: ["历史", "社会"], color: "linear-gradient(135deg,#4c1d95,#7c3aed)", status: "available", rating: 4.2, year: 2016 },
  { title: "希腊文明史", author: "汤因比", cat: "history", lang: "中文", tags: ["历史", "文明"], color: "linear-gradient(135deg,#134e4a,#0d9488)", status: "available", rating: 4.6, year: 2007 },
  { title: "新加坡体育史", author: "吴俊刚", cat: "history", lang: "中文", tags: ["历史", "体育"], color: "linear-gradient(135deg,#1e3a5f,#2563eb)", status: "available", rating: 3.9, year: 2020 },
  { title: "中国思想史", author: "葛兆光", cat: "history", lang: "中文", tags: ["历史", "思想"], color: "linear-gradient(135deg,#831843,#db2777)", status: "borrowed", rating: 4.5, year: 2009 },
  { title: "新加坡华文报业史", author: "许源泰", cat: "history", lang: "中文", tags: ["历史", "媒体"], color: "linear-gradient(135deg,#0f4c81,#1a6bb5)", status: "available", rating: 4.1, year: 2023 },
  { title: "日本近代史", author: "坂本多加雄", cat: "history", lang: "中文", tags: ["历史", "日本"], color: "linear-gradient(135deg,#7c3aed,#a855f7)", status: "available", rating: 4.4, year: 2008 },
  { title: "新加坡宗教多元史", author: "李焯然", cat: "history", lang: "中文", tags: ["历史", "宗教"], color: "linear-gradient(135deg,#dc2626,#f97316)", status: "available", rating: 4.3, year: 2021 },
  { title: "中国科技史", author: "李约瑟", cat: "history", lang: "中文", tags: ["历史", "科技"], color: "linear-gradient(135deg,#059669,#10b981)", status: "available", rating: 4.8, year: 2005 },
  { title: "新加坡环境史", author: "黄坚立", cat: "history", lang: "中文", tags: ["历史", "环境"], color: "linear-gradient(135deg,#0891b2,#06b6d4)", status: "available", rating: 4.0, year: 2022 },
  { title: "中国文化史", author: "柳诒徵", cat: "history", lang: "中文", tags: ["历史", "文化"], color: "linear-gradient(135deg,#be185d,#ec4899)", status: "reserve", rating: 4.5, year: 2003 },
  { title: "新加坡华人饮食史", author: "陈煜", cat: "history", lang: "中文", tags: ["历史", "饮食"], color: "linear-gradient(135deg,#92400e,#d97706)", status: "available", rating: 4.2, year: 2024 },
  { title: "中国哲学史", author: "冯友兰", cat: "history", lang: "中文", tags: ["历史", "哲学"], color: "linear-gradient(135deg,#1e40af,#3b82f6)", status: "available", rating: 4.7, year: 2002 },
  { title: "新加坡华人节庆史", author: "柯木林", cat: "history", lang: "中文", tags: ["历史", "文化"], color: "linear-gradient(135deg,#065f46,#34d399)", status: "available", rating: 4.1, year: 2023 },
  { title: "中国经济史", author: "吴承明", cat: "history", lang: "中文", tags: ["历史", "经济"], color: "linear-gradient(135deg,#374151,#6b7280)", status: "available", rating: 4.4, year: 2006 },
  { title: "新加坡华人艺术史", author: "许源泰", cat: "history", lang: "中文", tags: ["历史", "艺术"], color: "linear-gradient(135deg,#7c2d12,#ea580c)", status: "available", rating: 4.0, year: 2024 },
  { title: "中国军事史", author: "白寿彝", cat: "history", lang: "中文", tags: ["历史", "军事"], color: "linear-gradient(135deg,#4c1d95,#7c3aed)", status: "borrowed", rating: 4.3, year: 2004 },
  { title: "新加坡华人音乐史", author: "庄钦永", cat: "history", lang: "中文", tags: ["历史", "音乐"], color: "linear-gradient(135deg,#134e4a,#0d9488)", status: "available", rating: 3.9, year: 2022 },
  { title: "中国法律史", author: "张晋藩", cat: "history", lang: "中文", tags: ["历史", "法律"], color: "linear-gradient(135deg,#1e3a5f,#2563eb)", status: "available", rating: 4.2, year: 2007 },
  // history - English (~75 books)
  { title: "Singapore: A Biography", author: "Mark Ravinder Frost", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#831843,#db2777)", status: "available", rating: 4.6, year: 2009 },
  { title: "The Singapore Story", author: "Lee Kuan Yew", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#0f4c81,#1a6bb5)", status: "borrowed", rating: 4.9, year: 2000 },
  { title: "From Third World to First", author: "Lee Kuan Yew", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#7c3aed,#a855f7)", status: "available", rating: 4.8, year: 2000 },
  { title: "A History of Singapore", author: "C.M. Turnbull", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#dc2626,#f97316)", status: "available", rating: 4.5, year: 2009 },
  { title: "The Fall of Singapore", author: "Frank Owen", cat: "history", lang: "English", tags: ["history", "war"], color: "linear-gradient(135deg,#059669,#10b981)", status: "available", rating: 4.4, year: 2001 },
  { title: "Raffles and the British Invasion of Java", author: "Tim Hannigan", cat: "history", lang: "English", tags: ["history", "colonial"], color: "linear-gradient(135deg,#0891b2,#06b6d4)", status: "available", rating: 4.2, year: 2012 },
  { title: "Southeast Asia: A History", author: "D.G.E. Hall", cat: "history", lang: "English", tags: ["history", "Southeast Asia"], color: "linear-gradient(135deg,#be185d,#ec4899)", status: "available", rating: 4.5, year: 2002 },
  { title: "Empires of the Monsoon", author: "Richard Hall", cat: "history", lang: "English", tags: ["history", "Asia"], color: "linear-gradient(135deg,#92400e,#d97706)", status: "available", rating: 4.3, year: 2003 },
  { title: "The Straits Chinese", author: "Tan Chee Beng", cat: "history", lang: "English", tags: ["history", "Peranakan"], color: "linear-gradient(135deg,#1e40af,#3b82f6)", status: "available", rating: 4.4, year: 2004 },
  { title: "Sapiens: A Brief History of Humankind", author: "Yuval Noah Harari", cat: "history", lang: "English", tags: ["history", "humanity"], color: "linear-gradient(135deg,#065f46,#34d399)", status: "borrowed", rating: 4.9, year: 2015 },
  { title: "The Guns of August", author: "Barbara Tuchman", cat: "history", lang: "English", tags: ["history", "war"], color: "linear-gradient(135deg,#374151,#6b7280)", status: "available", rating: 4.6, year: 2004 },
  { title: "Singapore: Unlikely Power", author: "John Curtis Perry", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#7c2d12,#ea580c)", status: "available", rating: 4.3, year: 2017 },
  { title: "The Malay World of Southeast Asia", author: "Virginia Matheson Hooker", cat: "history", lang: "English", tags: ["history", "Malay"], color: "linear-gradient(135deg,#4c1d95,#7c3aed)", status: "available", rating: 4.2, year: 2003 },
  { title: "A History of Modern Singapore", author: "Lim Choo Hoon", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#134e4a,#0d9488)", status: "available", rating: 4.1, year: 2010 },
  { title: "The Second World War", author: "Antony Beevor", cat: "history", lang: "English", tags: ["history", "war"], color: "linear-gradient(135deg,#1e3a5f,#2563eb)", status: "available", rating: 4.7, year: 2012 },
  { title: "Singapore's Founding Myths", author: "Loh Kah Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#831843,#db2777)", status: "reserve", rating: 4.0, year: 2013 },
  { title: "The Silk Roads", author: "Peter Frankopan", cat: "history", lang: "English", tags: ["history", "world"], color: "linear-gradient(135deg,#0f4c81,#1a6bb5)", status: "available", rating: 4.7, year: 2015 },
  { title: "Colonial Singapore", author: "Brenda Yeoh", cat: "history", lang: "English", tags: ["history", "colonial"], color: "linear-gradient(135deg,#7c3aed,#a855f7)", status: "available", rating: 4.3, year: 2003 },
  { title: "The Rise and Fall of the British Empire", author: "Lawrence James", cat: "history", lang: "English", tags: ["history", "empire"], color: "linear-gradient(135deg,#dc2626,#f97316)", status: "available", rating: 4.5, year: 2001 },
  { title: "Singapore: The Air-Conditioned Nation", author: "Cherian George", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#059669,#10b981)", status: "available", rating: 4.2, year: 2000 },
  { title: "The Peranakan World", author: "Gretchen Liu", cat: "history", lang: "English", tags: ["history", "Peranakan"], color: "linear-gradient(135deg,#0891b2,#06b6d4)", status: "available", rating: 4.4, year: 2006 },
  { title: "Postwar: A History of Europe Since 1945", author: "Tony Judt", cat: "history", lang: "English", tags: ["history", "Europe"], color: "linear-gradient(135deg,#be185d,#ec4899)", status: "available", rating: 4.8, year: 2005 },
  { title: "Singapore's Little India", author: "Rajesh Rai", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#92400e,#d97706)", status: "available", rating: 4.1, year: 2014 },
  { title: "The History of the Decline and Fall of the Roman Empire", author: "Edward Gibbon", cat: "history", lang: "English", tags: ["history", "Rome"], color: "linear-gradient(135deg,#1e40af,#3b82f6)", status: "available", rating: 4.7, year: 2001 },
  { title: "Kampong Days: Village Life in Singapore", author: "Lim How Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#065f46,#34d399)", status: "available", rating: 4.3, year: 2007 },
  { title: "The Fate of Rome", author: "Kyle Harper", cat: "history", lang: "English", tags: ["history", "Rome"], color: "linear-gradient(135deg,#374151,#6b7280)", status: "available", rating: 4.4, year: 2017 },
  { title: "Singapore's Chinatown", author: "Gretchen Liu", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#7c2d12,#ea580c)", status: "borrowed", rating: 4.2, year: 2001 },
  { title: "The Anarchy", author: "William Dalrymple", cat: "history", lang: "English", tags: ["history", "India"], color: "linear-gradient(135deg,#4c1d95,#7c3aed)", status: "available", rating: 4.6, year: 2019 },
  { title: "Singapore's Geylang", author: "Loh Kah Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#134e4a,#0d9488)", status: "available", rating: 4.0, year: 2009 },
  { title: "The Crusades", author: "Thomas Asbridge", cat: "history", lang: "English", tags: ["history", "medieval"], color: "linear-gradient(135deg,#1e3a5f,#2563eb)", status: "available", rating: 4.5, year: 2010 },
  { title: "Singapore's Jurong", author: "Tan Tai Yong", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#831843,#db2777)", status: "available", rating: 3.9, year: 2011 },
  { title: "The Ottoman Empire", author: "Lord Kinross", cat: "history", lang: "English", tags: ["history", "empire"], color: "linear-gradient(135deg,#0f4c81,#1a6bb5)", status: "available", rating: 4.4, year: 2003 },
  { title: "Singapore's Orchard Road", author: "Gretchen Liu", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#7c3aed,#a855f7)", status: "reserve", rating: 4.1, year: 2012 },
  { title: "The Mongol Empire", author: "John Man", cat: "history", lang: "English", tags: ["history", "empire"], color: "linear-gradient(135deg,#dc2626,#f97316)", status: "available", rating: 4.3, year: 2004 },
  { title: "Singapore's Tanjong Pagar", author: "Tan Tai Yong", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#059669,#10b981)", status: "available", rating: 4.0, year: 2013 },
  { title: "The Scramble for Africa", author: "Thomas Pakenham", cat: "history", lang: "English", tags: ["history", "Africa"], color: "linear-gradient(135deg,#0891b2,#06b6d4)", status: "available", rating: 4.5, year: 2002 },
  { title: "Singapore's Katong", author: "Lim How Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#be185d,#ec4899)", status: "available", rating: 4.1, year: 2014 },
  { title: "The Vietnam War", author: "Geoffrey Ward", cat: "history", lang: "English", tags: ["history", "war"], color: "linear-gradient(135deg,#92400e,#d97706)", status: "available", rating: 4.6, year: 2017 },
  { title: "Singapore's Queenstown", author: "Loh Kah Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#1e40af,#3b82f6)", status: "available", rating: 3.9, year: 2015 },
  { title: "The Korean War", author: "Max Hastings", cat: "history", lang: "English", tags: ["history", "war"], color: "linear-gradient(135deg,#065f46,#34d399)", status: "borrowed", rating: 4.5, year: 2010 },
  { title: "Singapore's Bukit Timah", author: "Tan Tai Yong", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#374151,#6b7280)", status: "available", rating: 4.0, year: 2016 },
  { title: "The Cold War", author: "John Lewis Gaddis", cat: "history", lang: "English", tags: ["history", "politics"], color: "linear-gradient(135deg,#7c2d12,#ea580c)", status: "available", rating: 4.7, year: 2005 },
  { title: "Singapore's Sembawang", author: "Lim How Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#4c1d95,#7c3aed)", status: "available", rating: 3.8, year: 2017 },
  { title: "The American Civil War", author: "James McPherson", cat: "history", lang: "English", tags: ["history", "war"], color: "linear-gradient(135deg,#134e4a,#0d9488)", status: "available", rating: 4.8, year: 2003 },
  { title: "Singapore's Woodlands", author: "Loh Kah Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#1e3a5f,#2563eb)", status: "reserve", rating: 3.9, year: 2018 },
  { title: "The French Revolution", author: "William Doyle", cat: "history", lang: "English", tags: ["history", "Europe"], color: "linear-gradient(135deg,#831843,#db2777)", status: "available", rating: 4.5, year: 2002 },
  { title: "Singapore's Punggol", author: "Tan Tai Yong", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#0f4c81,#1a6bb5)", status: "available", rating: 3.8, year: 2019 },
  { title: "The Industrial Revolution", author: "Pat Hudson", cat: "history", lang: "English", tags: ["history", "economy"], color: "linear-gradient(135deg,#7c3aed,#a855f7)", status: "available", rating: 4.3, year: 2004 },
  { title: "Singapore's Pasir Ris", author: "Lim How Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#dc2626,#f97316)", status: "available", rating: 3.9, year: 2020 },
  { title: "The Renaissance", author: "Paul Johnson", cat: "history", lang: "English", tags: ["history", "Europe"], color: "linear-gradient(135deg,#059669,#10b981)", status: "available", rating: 4.4, year: 2000 },
  { title: "Singapore's Tampines", author: "Loh Kah Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#0891b2,#06b6d4)", status: "available", rating: 3.8, year: 2021 },
  { title: "The Age of Exploration", author: "Felipe Fernandez-Armesto", cat: "history", lang: "English", tags: ["history", "exploration"], color: "linear-gradient(135deg,#be185d,#ec4899)", status: "borrowed", rating: 4.5, year: 2006 },
  { title: "Singapore's Bedok", author: "Tan Tai Yong", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#92400e,#d97706)", status: "available", rating: 3.9, year: 2022 },
  { title: "The Reformation", author: "Diarmaid MacCulloch", cat: "history", lang: "English", tags: ["history", "Europe"], color: "linear-gradient(135deg,#1e40af,#3b82f6)", status: "available", rating: 4.6, year: 2003 },
  { title: "Singapore's Ang Mo Kio", author: "Lim How Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#065f46,#34d399)", status: "available", rating: 3.8, year: 2023 },
  { title: "The Black Death", author: "John Kelly", cat: "history", lang: "English", tags: ["history", "pandemic"], color: "linear-gradient(135deg,#374151,#6b7280)", status: "available", rating: 4.4, year: 2005 },
  { title: "Singapore's Bishan", author: "Loh Kah Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#7c2d12,#ea580c)", status: "reserve", rating: 3.9, year: 2024 },
  { title: "The Magna Carta", author: "David Starkey", cat: "history", lang: "English", tags: ["history", "law"], color: "linear-gradient(135deg,#4c1d95,#7c3aed)", status: "available", rating: 4.2, year: 2015 },
  { title: "Singapore's Toa Payoh", author: "Tan Tai Yong", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#134e4a,#0d9488)", status: "available", rating: 4.0, year: 2018 },
  { title: "The Enlightenment", author: "Roy Porter", cat: "history", lang: "English", tags: ["history", "philosophy"], color: "linear-gradient(135deg,#1e3a5f,#2563eb)", status: "available", rating: 4.5, year: 2001 },
  { title: "Singapore's Clementi", author: "Lim How Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#831843,#db2777)", status: "available", rating: 3.9, year: 2019 },
  { title: "The Age of Revolution", author: "Eric Hobsbawm", cat: "history", lang: "English", tags: ["history", "world"], color: "linear-gradient(135deg,#0f4c81,#1a6bb5)", status: "available", rating: 4.7, year: 2000 },
  { title: "Singapore's Yishun", author: "Loh Kah Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#7c3aed,#a855f7)", status: "available", rating: 3.8, year: 2020 },
  { title: "The Age of Empire", author: "Eric Hobsbawm", cat: "history", lang: "English", tags: ["history", "empire"], color: "linear-gradient(135deg,#dc2626,#f97316)", status: "borrowed", rating: 4.6, year: 2000 },
  { title: "Singapore's Hougang", author: "Tan Tai Yong", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#059669,#10b981)", status: "available", rating: 3.9, year: 2021 },
  { title: "The Age of Extremes", author: "Eric Hobsbawm", cat: "history", lang: "English", tags: ["history", "world"], color: "linear-gradient(135deg,#0891b2,#06b6d4)", status: "available", rating: 4.7, year: 2000 },
  { title: "Singapore's Sengkang", author: "Lim How Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#be185d,#ec4899)", status: "available", rating: 3.8, year: 2022 },
  { title: "The Peloponnesian War", author: "Donald Kagan", cat: "history", lang: "English", tags: ["history", "ancient"], color: "linear-gradient(135deg,#92400e,#d97706)", status: "available", rating: 4.5, year: 2003 },
  { title: "Singapore's Jurong West", author: "Loh Kah Seng", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#1e40af,#3b82f6)", status: "reserve", rating: 3.9, year: 2023 },
  { title: "The Thirty Years War", author: "C.V. Wedgwood", cat: "history", lang: "English", tags: ["history", "war"], color: "linear-gradient(135deg,#065f46,#34d399)", status: "available", rating: 4.4, year: 2005 },
  { title: "Singapore's Choa Chu Kang", author: "Tan Tai Yong", cat: "history", lang: "English", tags: ["history", "Singapore"], color: "linear-gradient(135deg,#374151,#6b7280)", status: "available", rating: 3.8, year: 2024 }
]
